In [1]:
#Import necessory libraries
import selenium
import pandas as pd
import time
from selenium import webdriver
from selenium.common.exceptions import NoSuchElementException,ElementClickInterceptedException, ElementNotVisibleException
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.by import By

In [9]:
driver = webdriver.Chrome(r"C:\Users\ABHINANDAN\Desktop\chromedriver.exe")

In [10]:
url = "https://www.yatra.com/"
driver.get(url)
time.sleep(3)

In [11]:
driver.find_element_by_xpath("/html/body/div[3]/div/section/div[1]/div/div[1]/section/div/div/div/div[1]/div[3]/div[2]/input").click()
time.sleep(3)

In [12]:
#making list of locations
city_lst = ['New Delhi', 'Mumbai', 'Bangalore', 'Chennai','Hyderabad ','Goa ','Kolkata ','Jaipur ','Lucknow ']

In [13]:
#defining lists for the data
airline_name=[]
depart_time = []
arrival_time = []
duration=[]
stops = []
source = []
destination = []
date=[]
meal=[]
price=[]
loc=[]

In [14]:
for x in city_lst:
    for y in city_lst:
        if x!=y:            
            source = driver.find_element_by_xpath("//div[@class='input-holder pb-2 bdr-btm']/input")
            time.sleep(2)
            source.clear() 
            source.send_keys(x)
            time.sleep(2)
            
            destination = driver.find_element_by_xpath("//div[@class='input-holder  bdr-btm pb-2']/input")
            time.sleep(2)
            destination.click()
            destination.clear()
            time.sleep(2)
            destination.send_keys(y)
            time.sleep(2)
            
            try:
                driver.find_element_by_xpath("/html/body/section[2]/section/div[1]/div/div[1]").click()
            except NoSuchElementException:
                pass
            try:
                srch_btn = driver.find_element_by_xpath("//button[@class='fs-14 btn-submit cursor-pointer bold']")
                wait = WebDriverWait(driver, 10)
                wait.until(EC.visibility_of(srch_btn))
                srch_btn.click()
            except NoSuchElementException:
                pass
            time.sleep(0.5)
            #try:
                #butns = driver.find_elements_by_xpath("//li[@class='i-b scroll-elem text-center']")
               # butns[1].click()
            #except NoSuchElementException:
             #   pass
            #scrolling the page
            for _ in range(15):
                time.sleep(1)
                driver.execute_script("window.scrollBy(0,5000)")
                time.sleep(5)
            #clicking on view fare
            #buttons = driver.find_elements_by_xpath("//button[@autom='morefares']")
            #for i in buttons:
                #wait = WebDriverWait(driver, 10)
                #wait.until(EC.visibility_of(i))
               # time.sleep(0.5)
               # driver.execute_script("arguments[0].click();", i)
            try:
                driver.find_element_by_xpath("//div[@title='scroll to top']").click()
            except NoSuchElementException:
                pass
           #fetching name of airline
            try:
                for i in driver.find_elements_by_xpath("//div[@class='fs-13 airline-name no-pad col-8']/span"):
                    airline_name.append(i.text)
            except NoSuchElementException:
                pass
            #time of depart
            try:
                for i in driver.find_elements_by_xpath("//div[@class='i-b pr']"):
                    depart_time.append(i.text)
            except NoSuchElementException:
                pass
            #time of arrival
            try:
                for i in driver.find_elements_by_xpath("//div[@class='i-b pdd-0 text-left atime col-5']//p[1]"):
                    arrival_time.append(i.get_attribute("innerHTML").splitlines()[0][0:5])
            except NoSuchElementException:
                pass
            #duration
            try:
                for i in driver.find_elements_by_xpath("//div[@class='stop-cont pl-13']/p"):
                    duration.append(i.text)
            except NoSuchElementException:
                pass
            #number of stops
            try:
                for i in driver.find_elements_by_xpath("//div[@class=' font-lightgrey fs-10 tipsy i-b fs-10']/span[1]"):
                    stops.append(i.text)
            except NoSuchElementException:
                pass
            #tetching availability of meal
            try:
                for i in driver.find_elements_by_xpath("//div[@class='features pull-right fs-12 flex']/div[1]"):
                    meal.append(i.text)
            except NoSuchElementException:
                pass
            #locations
            try:
                for i in driver.find_elements_by_xpath("//p[@class='fs-10 font-lightgrey no-wrap city ellipsis']"):
                    loc.append(i.text)
            except NoSuchElementException:
                pass
            #fetching prices
            try:
                for i in driver.find_elements_by_xpath("//div[@class='i-b tipsy fare-summary-tooltip fs-18']"):
                    price.append(i.text)
            except NoSuchElementException:
                pass

In [23]:
print(len(price),len(airline_name),len(depart_time),len(arrival_time),len(duration),len(stops),len(meal),len(price))

5805 5805 5805 5805 5805 5805 5805 5805

In [19]:
source = loc[0:len(loc):2]
destination = loc[1:len(loc):2]

In [22]:
len(source), len(destination)

(5805, 5805)

In [24]:
#creating a dataframe
data = list(zip(airline_name,depart_time,arrival_time,duration,source,destination,meal,stops,price))
df = pd.DataFrame(data, columns = ["Airline","Departure_time","Time_of_arrival","Duration", "Source","Destination","Meal_availability","Number_of_stops","Price"])
df

,Airline,Departure_time,Time_of_arrival,Duration,Source,Destination,Meal_availability,Number_of_stops,Price
0,Air Asia,12:40,20:15,7h 35m,New Delhi,Mumbai,No Meal Fare,1 Stop,"5,953"
1,Air Asia,11:55,20:15,8h 20m,New Delhi,Mumbai,No Meal Fare,1 Stop,"5,953"
2,Air Asia,16:15,06:20,14h 05m,New Delhi,Mumbai,No Meal Fare,1 Stop,"5,953"
3,Go First,18:50,20:45,1h 55m,New Delhi,Mumbai,No Meal Fare,Non Stop,"5,954"
4,Go First,09:05,11:05,2h 00m,New Delhi,Mumbai,No Meal Fare,Non Stop,"5,954"
...,...,...,...,...,...,...,...,...,...
5800,Air India,08:55,08:20,23h 25m,Lucknow,Jaipur,No Meal Fare,1 Stop,"9,302"
5801,Air India,08:55,09:20,24h 25m,Lucknow,Jaipur,No Meal Fare,2 Stop(s),"16,287"
5802,Air India,14:45,09:20,18h 35m,Lucknow,Jaipur,No Meal Fare,2 Stop(s),"16,865"
5803,Air India,08:55,09:20,24h 25m,Lucknow,Jaipur,No Meal Fare,2 Stop(s),"16,865"
5804,Air India,15:30,09:20,17h 50m,Lucknow,Jaipur,Free Meal,3 Stop(s),"19,749"

In [25]:
#saving the data into csv file
df.to_csv(r"C:\Users\ABHINANDAN\Desktop\Flight_prices.csv")